version: '3.7'

services:
  db:
    image: postgres:10.12-alpine
    networks:
      - db
    volumes:
      - pgdata:/var/lib/postgresql/data
    env_file:
      - docker/db/.env

  app:
    build:
      context: .
      dockerfile: docker/app/Dockerfile_local
    networks:
      - backend
      - db
    volumes:
      - ./:/app
    command: uvicorn main:app --reload --host 0.0.0.0 --port 3000
    env_file:
      - docker/app/.env
      - docker/db/.env
    ports:
      - 3000:3000
    depends_on:
      - db

networks:
  db:
    driver: bridge
  backend:
    driver: bridge

volumes:
    pgdata:
      name: chatrooms_db
      driver: local
