-- upgrade --
CREATE TABLE IF NOT EXISTS "token" (
    "key" VARCHAR(40) NOT NULL  PRIMARY KEY,
    "user_id" INT NOT NULL UNIQUE REFERENCES "user" ("id") ON DELETE CASCADE
);;
CREATE TABLE IF NOT EXISTS "user" (
    "id" SERIAL NOT NULL PRIMARY KEY,
    "email" VARCHAR(100) NOT NULL UNIQUE,
    "password" VARCHAR(100) NOT NULL,
    "date_join" TIMESTAMPTZ NOT NULL  DEFAULT CURRENT_TIMESTAMP
);-- downgrade --
DROP TABLE IF EXISTS "token";
DROP TABLE IF EXISTS "user";
