name: Python tests

on:
  pull_request:
    branches: [ "main" ]

jobs:
  container-job:

    runs-on: ubuntu-latest
    container: python:3.8-slim-buster

    services:
      postgres:
        image: postgres:10.12-alpine
        env:
          POSTGRES_DB: chatrooms
          POSTGRES_USER: chatrooms
          POSTGRES_PASSWORD: chatrooms
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install -r requirements/base.txt -r requirements/testing.txt
      - name: Test with pytest
        run: |
          pytest
        env:
          POSTGRES_HOST: postgres
          POSTGRES_PORT: 5432
          POSTGRES_DB: chatrooms
          POSTGRES_USER: chatrooms
          POSTGRES_PASSWORD: chatrooms
          SECRET_KEY: 'change_me'
          MAIL_SERVER: ''
          MAIL_PORT: 0
          MAIL_USERNAME: ''
          MAIL_PASSWORD: ''
