name: Python tests

on:
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:10.12-alpine
        env:
          POSTGRES_DB: chatrooms
          POSTGRES_USER: chatrooms
          POSTGRES_PASSWORD: chatrooms
        ports:
          - 5432:5432

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.8'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install -r requirements/base.txt -r requirements/testing.txt
    - name: Test with pytest
      run: |
        pytest
    env:
      POSTGRES_HOST: localhost
      POSTGRES_PORT: 5432
      POSTGRES_DB: chatrooms
      POSTGRES_USER: chatrooms
      POSTGRES_PASSWORD: chatrooms
      SECRET_KEY: 'change_me'
      MAIL_SERVER: ''
      MAIL_PORT: 0
      MAIL_USERNAME: ''
      MAIL_PASSWORD: ''
